// Clerk dark theme appearance config — matches Patchwork visual tokens.
export const clerkDarkAppearance = {
  variables: {
    colorBackground: '#161920',
    colorInputBackground: '#1e222d',
    colorText: '#e8eaf0',
    colorTextSecondary: '#8b92a8',
    colorInputText: '#e8eaf0',
    colorPrimary: '#00d4a8',
    colorDanger: '#ff6b6b',
    colorNeutral: '#e8eaf0',
    borderRadius: '0.75rem',
    fontFamily: 'IBM Plex Sans, sans-serif',
  },
  elements: {
    card: 'border border-[#2a2f3d] shadow-none bg-[#161920]',
    formButtonPrimary: 'font-mono tracking-wide',
    formFieldLabel: 'text-[#e8eaf0]',
    formFieldInput: 'text-[#e8eaf0] bg-[#1e222d] border-[#2a2f3d]',
    formFieldInputShowPasswordButton: 'text-[#8b92a8]',
    identityPreviewText: 'text-[#e8eaf0]',
    identityPreviewEditButton: 'text-[#00d4a8]',
    headerTitle: 'text-[#e8eaf0]',
    headerSubtitle: 'text-[#8b92a8]',
    dividerText: 'text-[#8b92a8]',
    dividerLine: 'bg-[#2a2f3d]',
    footerActionText: 'text-[#8b92a8]',
    footerActionLink: 'text-[#00d4a8]',
    // Social (OAuth) buttons: white background so provider logos/text are legible
    socialButtonsBlockButton: 'bg-white hover:bg-gray-100 border border-gray-200 text-gray-900',
    socialButtonsBlockButtonText: 'text-gray-900 font-medium',
    // UserButton popover
    userButtonPopoverCard: 'bg-[#1e222d] border border-[#2a2f3d]',
    userButtonPopoverActionButton: 'text-[#e8eaf0] hover:bg-[#2a2f3d]',
    userButtonPopoverActionButtonText: 'text-[#e8eaf0]',
    userButtonPopoverActionButtonIcon: 'text-[#8b92a8]',
    userButtonPopoverFooter: 'text-[#8b92a8]',
    userPreviewMainIdentifier: 'text-[#e8eaf0]',
    userPreviewSecondaryIdentifier: 'text-[#8b92a8]',
  },
};
